# -*- coding: utf-8 -*-
"""daily-temp-and-precip-averages_from_monthly-averages-data_release.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cpdOLf4sVwc8mWy4C9fgoMrRp4ToxPst
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.interpolate import CubicSpline

# https://github.com/jambao24/MATLAB_climatedata_modeling/blob/main/TempSimul3%20original%20code.rtf

# assign the monthly average temp for each day of a month to a numpy array with 365 elements
# assumption: temps is an numpy array with 12 elements
def assign_monthly_avg_to_days(temps):
  temps_out = np.zeros(365)
  # initialize the values of temps_out to the monthly averages in temps
  # daily average for each day is the monthly average for that month
  temps_out[0:31] = temps[0]
  temps_out[31:59] = temps[1]
  temps_out[59:90] = temps[2]
  temps_out[90:120] = temps[3]
  temps_out[120:151] = temps[4]
  temps_out[151:181] = temps[5]
  temps_out[181:212] = temps[6]
  temps_out[212:243] = temps[7]
  temps_out[243:273] = temps[8]
  temps_out[273:304] = temps[9]
  temps_out[304:334] = temps[10]
  temps_out[334:365] = temps[11]
  return temps_out

# assumption: annual_temps is a numpy array with 365 elements
def calculate_mean_monthly_temps(annual_temps):
  monthly_temps = np.zeros(12)
  monthly_temps[0] = np.mean(annual_temps[0:31])
  monthly_temps[1] = np.mean(annual_temps[31:59])
  monthly_temps[2] = np.mean(annual_temps[59:90])
  monthly_temps[3] = np.mean(annual_temps[90:120])
  monthly_temps[4] = np.mean(annual_temps[120:151])
  monthly_temps[5] = np.mean(annual_temps[151:181])
  monthly_temps[6] = np.mean(annual_temps[181:212])
  monthly_temps[7] = np.mean(annual_temps[212:243])
  monthly_temps[8] = np.mean(annual_temps[243:273])
  monthly_temps[9] = np.mean(annual_temps[273:304])
  monthly_temps[10] = np.mean(annual_temps[304:334])
  monthly_temps[11] = np.mean(annual_temps[334:365])
  monthly_temps = np.round(monthly_temps, 2)
  return monthly_temps

# assumption: annual_precip is a numpy array with 365 elements
def calculate_monthly_precip_from_daily(annual_precip):
    monthly_precip = np.zeros(12)
    monthly_precip[0] = np.sum(annual_precip[0:31])
    monthly_precip[1] = np.sum(annual_precip[31:59])
    monthly_precip[2] = np.sum(annual_precip[59:90])
    monthly_precip[3] = np.sum(annual_precip[90:120])
    monthly_precip[4] = np.sum(annual_precip[120:151])
    monthly_precip[5] = np.sum(annual_precip[151:181])
    monthly_precip[6] = np.sum(annual_precip[181:212])
    monthly_precip[7] = np.sum(annual_precip[212:243])
    monthly_precip[8] = np.sum(annual_precip[243:273])
    monthly_precip[9] = np.sum(annual_precip[273:304])
    monthly_precip[10] = np.sum(annual_precip[304:334])
    monthly_precip[11] = np.sum(annual_precip[334:365])
    return monthly_precip

# assumption: monthly_precip is a numpy array with 12 elements
def assign_initial_daily_precip(monthly_precip):
  precip_daily = np.zeros(365)
  precip_daily[0:31] = monthly_precip[0]/31
  precip_daily[31:59] = monthly_precip[1]/28
  precip_daily[59:90] = monthly_precip[2]/31
  precip_daily[90:120] = monthly_precip[3]/30
  precip_daily[120:151] = monthly_precip[4]/31
  precip_daily[151:181] = monthly_precip[5]/30
  precip_daily[181:212] = monthly_precip[6]/31
  precip_daily[212:243] = monthly_precip[7]/31
  precip_daily[243:273] = monthly_precip[8]/30
  precip_daily[273:304] = monthly_precip[9]/31
  precip_daily[304:334] = monthly_precip[10]/30
  precip_daily[334:365] = monthly_precip[11]/31
  return precip_daily

# assumption: annual_precip is a numpy array with 365 elements
def calculate_monthly_precip_from_daily(annual_precip):
    monthly_precip = np.zeros(12)
    monthly_precip[0] = np.sum(annual_precip[0:31])
    monthly_precip[1] = np.sum(annual_precip[31:59])
    monthly_precip[2] = np.sum(annual_precip[59:90])
    monthly_precip[3] = np.sum(annual_precip[90:120])
    monthly_precip[4] = np.sum(annual_precip[120:151])
    monthly_precip[5] = np.sum(annual_precip[151:181])
    monthly_precip[6] = np.sum(annual_precip[181:212])
    monthly_precip[7] = np.sum(annual_precip[212:243])
    monthly_precip[8] = np.sum(annual_precip[243:273])
    monthly_precip[9] = np.sum(annual_precip[273:304])
    monthly_precip[10] = np.sum(annual_precip[304:334])
    monthly_precip[11] = np.sum(annual_precip[334:365])
    return monthly_precip

# attempted spline for high and low averages.
# Use Cubic Spline function to fit the daily means to the monthly means;
# (This requires picking a day within each month for which we think the daily mean will equal the monthly mean)
# Run the interpolation over 2 calendar years (730 days) so we get a smooth transition from end of old year to beginning of new year
# Compute a new set of annual daily means using the last 40 days of old year, first 40 days of new year, and averaging the rest of Old Year and New Year in between.
# (We discard the first 40 days of Old Year and the last 40 days of New Year)

def compute_daily_temps_spline(interpol_x, monthly_avgs, timespan):
    interpol_y = np.zeros(np.size(interpol_x))
    interpol_y[0:12] = monthly_avgs
    interpol_y[12:24] = monthly_avgs
    interpol = CubicSpline(interpol_x, interpol_y)
    temps_new = interpol(timespan)

    temps_new_ = np.zeros(365)
    temps_new_[0:40] = temps_new[365:40+365]
    temps_new_[-40:] = temps_new[365-40:365]
    temps_new_[40:365-40] = (np.array(temps_new[40:365-40]) + np.array(temps_new[365+40:730-40]))/2.0

    return temps_new_

# temps_mth = list of monthly average temps (array of size 12), temps_daily = daily average temps assigned to its corresponding monthly average
# should return 'smoothed' daily average temps
def compute_daily_temps_runAvg(temps_daily, temps_mth, cycle_val):
  # attempt to implement the running average method from my MATLAB script
  temps_temp = np.zeros(730)
  # start out with the daily avgs set to the monthly avgs
  temps_temp[0:365] = temps_daily[0:365]
  temps_temp[365:730] = temps_daily[0:365]

  # run smoothing operation for n cycles (n = cycle_val parameter)
  for i in range(0, cycle_val):
    # for each cycle, re-compute average daily precip based on 4-day running average across 2 calendar years
    for j in range(0, 730-4):
      temps_temp[j+2] = np.mean(temps_temp[j:j+4])

    # truncate edges of 2-year run
    temps_daily_new_runAvg = np.zeros(365)
    temps_daily_new_runAvg[0:10] = temps_temp[365:10+365]
    temps_daily_new_runAvg[-10:] = temps_temp[365-10:365]
    temps_daily_new_runAvg[10:365-10] = (np.array(temps_temp[10:365-10]) + np.array(temps_temp[365+10:730-10]))/2.0

    # compute monthly totals from smoothed daily averages
    temps_daily_new_mths_rA = calculate_mean_monthly_temps(temps_daily_new_runAvg)
    temps_diff_ = temps_daily_new_mths_rA - temps_mth

    # correct each daily average by how much the corresponding monthly average is off from the starting data by
    # but only for each cycle where this will run next
    if i < cycle_val:
      temps_daily_new_runAvg[0:31] -= temps_diff_[0]
      temps_daily_new_runAvg[31:59] -= temps_diff_[1]
      temps_daily_new_runAvg[59:90] -= temps_diff_[2]
      temps_daily_new_runAvg[90:120] -= temps_diff_[3]
      temps_daily_new_runAvg[120:151] -= temps_diff_[4]
      temps_daily_new_runAvg[151:181] -= temps_diff_[5]
      temps_daily_new_runAvg[181:212] -= temps_diff_[6]
      temps_daily_new_runAvg[212:243] -= temps_diff_[7]
      temps_daily_new_runAvg[243:273] -= temps_diff_[8]
      temps_daily_new_runAvg[273:304] -= temps_diff_[9]
      temps_daily_new_runAvg[304:334] -= temps_diff_[10]
      temps_daily_new_runAvg[334:365] -= temps_diff_[11]

      # reassign the current daily precip averages to the temp array to be smoothed in the next cycle
      temps_temp[0:365] = temps_daily_new_runAvg[0:365]
      temps_temp[365:730] = temps_daily_new_runAvg[0:365]


    # smoothing operation by re-assigning the normalized daily average to be the 21-day mean of the unnormalized daily average
    temps_temp_ = np.zeros(730)
    for k in range(0+10, 730-10):
      temps_temp_[k] = np.mean(temps_temp[k-10:k+11])

    temps_temp_[0:10] = temps_temp[365:365+10]
    temps_temp_[730-10:] = temps_temp[365-10:365]
    temps_temp = temps_temp_

  return temps_temp

# https://www.omnicalculator.com/physics/relative-humidity#how-to-calculate-relative-humidity
def calculate_wetbulb(drybulb, dp_temps):
  rel_humid = np.zeros(365)
  c1 = 17.625
  c2 = 243.04
  vals1 = c1*dp_temps[0:365] / (dp_temps[0:365] + c2)
  vals2 = c1*drybulb[0:365] / (drybulb[0:365] + c2)
  rel_humid = 100*np.exp(vals1)/np.exp(vals2)

  # https://www.omnicalculator.com/physics/wet-bulb#how-to-calculate-the-wet-bulb-temperature
  '''
  T _w = T*arctan(0.151977*sqrt(RH+8.313659)) + 0.00391838*sqrt(RH^3)*arctan(0.023101*RH) − arctan(RH−1.676331) + arctan(T+RH) − 4.686035
  '''
  wetbulb = np.zeros(rel_humid.shape[0])
  # https://numpy.org/doc/stable/reference/generated/numpy.power.html
  c3 = np.power(rel_humid, 1.5)
  c4 = np.power(rel_humid+8.313659, 0.5)
  c5 = np.arctan(0.151977*c4)
  c6 = np.arctan(0.023101*rel_humid)
  c7 = np.arctan(rel_humid-1.676331)
  c8 = np.arctan(drybulb+rel_humid)
  wetbulb = drybulb*c5 + 0.00391838*c3*c6 - c7 + c8 - 4.686035
  return wetbulb

"""**Mount Hamilton climate averages**
https://en.wikipedia.org/wiki/Mount_Hamilton_(California)#Climate

9.8,9.3,10.7,12.9,16.8,21.7,25.9,25.8,23.6,18.6,12.6,9.2

6.9,6.2,7.3,8.9,12.7,17.5,22.2,21.9,19.7,14.9,9.5,6.3

3.9,3.2,3.8,4.8,8.6,13.3,18.4,18.1,15.7,11.3,6.3,3.3

128,122,112,56,33,7,0,1,4,34,76,120

http://www.unit-conversion.info/texttools/replace-text/
"""

# input monthly averages here from selected climate

# this is for Mount Hamilton east of San Jose CA/now fictional Volantis
'''
highs_mth = np.array([44.8,43.7,37.3,25.2,14.7,10.6,11.4,22.1,31.6,42.5,46.2,45.5])
lows_mth = np.array([32.6,32.5,23.7,11.6,2.1,-2.2,-2.2,7.3,15.6,25.5,31,32.5])
avgs_mth = np.array([38.7,38.1,30.5,18.4,8.4,4.2,4.6,14.7,23.6,34,38.6,39])
# adding the dewpoint stat
dewpoint_mth = np.array([26.5,26.6,18.1,6.6,-3.4,-5.8,-9.1,-6.9,4,15.7,20.1,24])
# adding precipitation
precip_mth = np.array([186,277,145,100,87,54,33,40,27,69,103,145])
''''''
highs_mth = np.array([28.2,28.1,28.7,29.8,27.9,26.4,25,26.1,27.4,29.6,29.8,28.7])
lows_mth = np.array([20.6,20.5,19.7,19.4,16.7,13.2,11.2,11.9,15.2,18.4,20.8,20.9])
avgs_mth = np.array([24.4,24.3,24.2,24.6,22.3,19.8,18.1,19,21.3,24,25.3,24.8])
# adding the dewpoint stat
dewpoint_mth = np.array([18.5,18.6,17.1,15.6,12.3,8.8,6.7,8.3,11,14,16.8,18])
# adding precipitation
precip_mth = np.array([186,177,145,100,67,54,63,70,57,89,113,161])
'''
# for fictional Dubai 2300 CE
highs_mth = np.array([32,33.2,36.8,41.1,44,45.6,46.1,46.1,44.9,41.9,37.5,34.5])
lows_mth = np.array([20.8,21.8,24.6,28.1,31.2,33.2,34.3,34.3,32.7,30.1,26.1,22.9])
avgs_mth = np.array([26.4,27.5,30.7,34.6,37.6,39.4,40.2,40.2,38.8,36,31.8,28.7])
# adding the dewpoint stat
dewpoint_mth = np.array([12.3,13,16.5,19.9,23.4,26.4,28.1,28.4,27.7,25,20.1,15.2])
# adding precipitation
precip_mth = np.array([8,15,22,5,0,0,0,0,0,11,3,12])

climate_name = "Fictional Dubai 2300"

time = np.linspace(0, 730, 730)

# https://stackoverflow.com/questions/48199077/elementwise-aggregation-average-of-values-in-a-list-of-numpy-arrays-with-same
#avgs_mth = np.mean([highs_mth, lows_mth], axis=0)
#print(avgs_mth)

# use running_average method to compute daily mean temps monthly mean temps

# initialize the values of high_temps, low_temps, and avg_temps to the monthly averages
# daily average for each day is the monthly average for that month
high_temps = assign_monthly_avg_to_days(highs_mth)
low_temps = assign_monthly_avg_to_days(lows_mth)
avg_temps = assign_monthly_avg_to_days(avgs_mth)

# for Volantis I used https://www.omnicalculator.com/physics/dew-point- above 18 = rounded to nearest 0.1, below 18 = rounded to nearest 0.5
dewpoint_temps = assign_monthly_avg_to_days(dewpoint_mth)
dp_temps_new = compute_daily_temps_runAvg(dewpoint_temps, dewpoint_mth, 50)
dp_mth_compute365 = calculate_mean_monthly_temps(dp_temps_new)

high_temps_new_ = compute_daily_temps_runAvg(high_temps, highs_mth, 50)

highs_mth_compute365 = calculate_mean_monthly_temps(high_temps_new_)
print(highs_mth_compute365 - highs_mth)
print(np.mean(high_temps_new_) - np.mean(high_temps))

low_temps_new_ = compute_daily_temps_runAvg(low_temps, lows_mth, 50)

lows_mth_compute365 = calculate_mean_monthly_temps(low_temps_new_)
print(lows_mth_compute365 - lows_mth)
print(np.mean(low_temps_new_) - np.mean(low_temps))

# compute new daily means from high and low temps
high_temps_new_ = 1.0*np.round(1*high_temps_new_, 2)
low_temps_new_ = 1.0*np.round(1*low_temps_new_, 2)
avg_temps_new_ = (np.array(low_temps_new_) + np.array(high_temps_new_))/2.0
#avg_temps_new_ = 1.0*np.round(1*avg_temps_new_, 2)
dp_temps_new_ = 1.0*np.round(1*dp_temps_new, 2)

wetbulb_high_dp = calculate_wetbulb(high_temps_new_[0:365], dp_temps_new_)
wetbulb_low_dp = calculate_wetbulb(low_temps_new_[0:365], dp_temps_new_)
wetbulb_avg_dp = calculate_wetbulb(avg_temps_new_[0:365], dp_temps_new_)


# https://datagy.io/matplotlib-title/
fig, ax = plt.subplots(figsize=(10,8))
#plt.figure(figsize = (10,8))
plt.title(climate_name + " average daily temperatures")
plt.xlabel("Day of year")
plt.ylabel("Temperature (deg C)")
plt.plot(time[0:365], high_temps_new_[0:365], 'g')
#plt.plot(time[0:365], high_temps, 'b')
plt.plot(time[0:365], low_temps_new_[0:365], 'g')
#plt.plot(time[0:365], low_temps, 'b')
plt.plot(time[0:365], avg_temps_new_[0:365], 'r')
#plt.plot(time[0:365], avg_temps, 'b')
#plt.plot(time[0:365], dewpoint_temps, 'b')
plt.plot(time[0:365], dp_temps_new_[0:365], 'y')
plt.plot(time[0:365], wetbulb_high_dp, 'purple')
#plt.plot(time[0:365], wetbulb_low_dp, 'purple')
plt.xlim(0, 365)
plt.ylim(10, 50)
ax.grid()
plt.show()

# https://pythonnumericalmethods.berkeley.edu/notebooks/chapter17.03-Cubic-Spline-Interpolation.html

# monthly averages here from _______ fictional climate)
#highs_mth = np.array([40.4,40.5,41.1,42.4,43.2,42.5,42.5,43.2,45.7,46.5,44.9,42.2])
#lows_mth = np.array([34.2,33.9,32.9,30,25.2,18.1,18.1,22.8,29.1,33.9,35.5,35.2])

time = np.linspace(0, 730, 730)

# https://stackoverflow.com/questions/48199077/elementwise-aggregation-average-of-values-in-a-list-of-numpy-arrays-with-same
avgs_mth = np.mean([highs_mth, lows_mth], axis=0)
#print(avgs_mth)

# initialize the values of high_temps, low_temps, and avg_temps to the monthly averages
# daily average for each day is the monthly average for that month
high_temps = assign_monthly_avg_to_days(highs_mth)
low_temps = assign_monthly_avg_to_days(lows_mth)
avg_temps = assign_monthly_avg_to_days(avgs_mth)

# Use Cubic Spline function to fit the daily means to the monthly means;
highs_interpol_x = [10,48,75,104,133,165,199,227,258,292,320,350,10+365,48+365,75+365,104+365,133+365,165+365,199+365,227+365,258+365,292+365,320+365,350+365]
high_temps_new_ = compute_daily_temps_spline(highs_interpol_x, highs_mth, time)

highs_mth_compute365 = calculate_mean_monthly_temps(high_temps_new_)
print(highs_mth_compute365 - highs_mth)
print(np.mean(high_temps_new_) - np.mean(high_temps))

# Use Cubic Spline function to fit the daily means to the monthly means;
lows_interpol_x = [13,47,75,104,136,165,199,227,258,287,315,352,13+365,47+365,75+365,104+365,136+365,165+365,199+365,227+365,258+365,287+365,315+365,352+365]
low_temps_new_ = compute_daily_temps_spline(lows_interpol_x, lows_mth, time)

lows_mth_compute365 = calculate_mean_monthly_temps(low_temps_new_)
print(lows_mth_compute365 - lows_mth)
print(np.mean(low_temps_new_) - np.mean(low_temps))

# compute new daily means from high and low temps
avg_temps_new_ = (np.array(low_temps_new_) + np.array(high_temps_new_))/2.0
avg_temps_new_ = np.round(avg_temps_new_, 2)
high_temps_new_ = np.round(high_temps_new_, 2)
low_temps_new_ = np.round(low_temps_new_, 2)

fig, ax = plt.subplots(figsize=(10,8))
#plt.figure(figsize = (10,8))
plt.plot(time[0:365], high_temps_new_, 'g')
plt.plot(time[0:365], high_temps, 'b')
plt.plot(time[0:365], low_temps_new_, 'g')
plt.plot(time[0:365], low_temps, 'b')
plt.plot(time[0:365], avg_temps_new_, 'r')
plt.xlim(0, 365)
#plt.ylim(-10, 50)
ax.grid()
plt.show()

# trying to compute daily precip from monthly precip averages

tim = np.linspace(0, 730, 730)

##precip_mth = np.array([356,391,134,53,12,2,3,0,0,8,37,89])
# initialize the values of dream_D_precip, dream_N_precip, and avg_temps to the monthly averages
# daily average for each day is the monthly average for that month
precip_daily = assign_initial_daily_precip(precip_mth)


p_time = np.linspace(0, 365, 365)

'''
https://weatherspark.com/y/137170/Average-Weather-in-Taipei-Taiwan-Year-Round#Sections-Rain
To show variation within the months and not just the monthly totals, we show the rainfall accumulated over a sliding 31-day period centered around each day of the year.
'''

'''
use convolution or something to get the 31-day moving average after getting the daily average for each day of the year
https://stackoverflow.com/questions/14313510/how-to-calculate-rolling-moving-average-using-python-numpy-scipy
'''

# attempt to implement the running average method from my MATLAB script
precip_temp = np.zeros(730)
# start out with the daily avgs set to the monthly avgs
precip_temp[0:365] = precip_daily[0:365]
precip_temp[365:730] = precip_daily[0:365]

# run smoothing operation for n cycles
cycle_val = 20
for i in range(0, cycle_val):
  # for each cycle, re-compute average daily precip based on 4-day running average across 2 calendar years
  for j in range(0, 730-4):
    precip_temp[j+2] = np.mean(precip_temp[j:j+4])

  # truncate edges of 2-year run
  precip_daily_new_runAvg = np.zeros(365)
  precip_daily_new_runAvg[0:10] = precip_temp[365:10+365]
  precip_daily_new_runAvg[-10:] = precip_temp[365-10:365]
  precip_daily_new_runAvg[10:365-10] = (np.array(precip_temp[10:365-10]) + np.array(precip_temp[365+10:730-10]))/2.0

  # compute monthly totals from smoothed daily averages
  precip_daily_new_mths_rA = calculate_monthly_precip_from_daily(precip_daily_new_runAvg)
  precip_diff_ = precip_daily_new_mths_rA - precip_mth

  # correct each daily average by how much the corresponding monthly average is off from the starting data by
  # but only for each cycle where this will run next
  if i < cycle_val:
    precip_daily_new_runAvg[0:31] -= precip_diff_[0]/31
    precip_daily_new_runAvg[31:59] -= precip_diff_[1]/28
    precip_daily_new_runAvg[59:90] -= precip_diff_[2]/31
    precip_daily_new_runAvg[90:120] -= precip_diff_[3]/30
    precip_daily_new_runAvg[120:151] -= precip_diff_[4]/31
    precip_daily_new_runAvg[151:181] -= precip_diff_[5]/30
    precip_daily_new_runAvg[181:212] -= precip_diff_[6]/31
    precip_daily_new_runAvg[212:243] -= precip_diff_[7]/31
    precip_daily_new_runAvg[243:273] -= precip_diff_[8]/30
    precip_daily_new_runAvg[273:304] -= precip_diff_[9]/31
    precip_daily_new_runAvg[304:334] -= precip_diff_[10]/30
    precip_daily_new_runAvg[334:365] -= precip_diff_[11]/31
    # reassign all negative values to equal 0; this is average precipitation
    precip_daily_new_runAvg[precip_daily_new_runAvg < 0] = 0
    # reassign the current daily precip averages to the temp array to be smoothed in the next cycle
    precip_temp[0:365] = precip_daily_new_runAvg[0:365]
    precip_temp[365:730] = precip_daily_new_runAvg[0:365]



precip_D_daily_new_mths_rA = calculate_monthly_precip_from_daily(precip_daily_new_runAvg)

print("Dream monthly precip totals from smoothing function: \n", np.round(precip_daily_new_mths_rA, decimals=2))
precip_diff_ = precip_daily_new_mths_rA - precip_mth
print("Diff from source data: \n", np.round(precip_diff_, decimals=2))

# attempt at implementing the 31-day running average sum for each day of the year for dream climate
# assumption: precip_D_daily_new_runAvg already contains the current simulated daily average precipitation
precip_daily_new_runAvg_base = np.zeros(730)
precip_daily_new_runAvg_base[0:365] = precip_daily_new_runAvg
precip_daily_new_runAvg_base[365:730] = precip_daily_new_runAvg
precip_daily_new_runAvg_sum = np.zeros(730)

for i in range(0+15, 730-15):
  precip_daily_new_runAvg_sum[i] = np.sum(precip_daily_new_runAvg_base[i-15:i+16])

precip_daily_new_runAvg_sum[0:15] = precip_daily_new_runAvg_sum[365:365+15]
precip_daily_new_runAvg_sum[730-15:] = precip_daily_new_runAvg_sum[365-15:365]

precip_daily_new_runAvg_sum_avg = np.zeros(365)
precip_daily_new_runAvg_sum_avg = precip_daily_new_runAvg_sum[0:365]/31


running_avg_yearly_sum = calculate_monthly_precip_from_daily(precip_daily_new_runAvg_sum_avg)
#print(running_avg_yearly_sum)
#print(np.sum(running_avg_yearly_sum))
#print(np.round(precip_daily_new_mths_rA, decimals=2))
#print(np.sum(precip_daily_new_mths_rA))

print("Monthly precip totals from 31-day moving average: \n", np.round(running_avg_yearly_sum, decimals=2))
print("Monthly precip totals (original): \n", precip_mth)
precip_diff_ = running_avg_yearly_sum - precip_mth
print("Diff from source data: \n", np.round(precip_diff_))



#plt.figure(figsize = (10,8))
fig, ax = plt.subplots(1, figsize = (10,8))
plt.title(climate_name + " average 31-day floating precipitation")
plt.xlabel("Day of year")
plt.ylabel("Precipitation (mm)")
plt.plot(tim[0:365], precip_daily_new_runAvg_sum[0:365], 'g')
#plt.plot(tim[0:365], np.multiply(31,precip_daily_new_runAvg[0:365]), 'r')
#plt.ylim(0, 210)
plt.xlim(0, 365)
ax.grid()
plt.show()


# plot precip
#plt.figure(figsize = (10,8))
fig, ax = plt.subplots(1, figsize = (10,8))
plt.title(climate_name + " average daily precipitation")
plt.xlabel("Day of year")
plt.ylabel("Precipitation (mm/day)")
plt.plot(tim[0:365], precip_daily, 'b')
plt.plot(tim[0:365], precip_daily_new_runAvg, 'r')
plt.plot(tim[0:365], precip_daily_new_runAvg_sum[0:365]/31, 'g')
#plt.ylim(0,7)
plt.xlim(0,365)
ax.grid()
plt.show()

# https://stackoverflow.com/questions/2891790/pretty-print-a-numpy-array-without-scientific-notation-and-with-given-precision
#print(precip_daily_new_runAvg_sum[0:365])

from google.colab import files

#https://stackoverflow.com/questions/49394737/exporting-data-from-google-colab-to-local-machine
#https://stackoverflow.com/questions/6081008/dump-a-numpy-array-into-a-csv-file

# https://stackoverflow.com/questions/32635911/convert-elements-of-an-array-from-scientific-notation-to-decimal-notation-in-pyt
# https://www.freecodecamp.org/news/dataframe-to-csv-how-to-save-pandas-dataframes-by-exporting/
avg_temps = np.zeros((365, 6))
avg_temps[:,0] = high_temps_new_[0:365]
avg_temps[:,1] = avg_temps_new_[0:365]
avg_temps[:,2] = low_temps_new_[0:365]
avg_temps[:,3] = dp_temps_new_[0:365]
avg_temps[:,4] = 1.0*np.round(wetbulb_highs_dp[0:365], 2)
avg_temps[:,5] = 1.0*np.round(precip_daily_new_runAvg_sum[0:365], 1)

np.set_printoptions(suppress=True, precision=2)
np.savetxt('daily_averages_.csv', avg_temps, delimiter=',',fmt='%f')

#np.savetxt('precip_daily_31dayavg.csv', precip_daily_new_runAvg_sum, delimiter=',',fmt='%f')